services:
  # Lambda シミュレーター用サービス
  yfinance-lambda-sim:
    image: public.ecr.aws/sam/build-python3.12
    environment:
      - EXECUTION_MODE=DOCKER
    volumes:
      - .:/var/task
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /var/task
    command: ["sam", "local", "start-api", "--host", "0.0.0.0", "--port", "3000"]
    ports:
      - "3000:3000"
  
  # 直接テスト用サービス（Lambda環境）
  yfinance-local:
    build:
      context: .
    environment:
      - EXECUTION_MODE=DOCKER
      - YFINANCE_API_URL=https://zwtiey61i2.execute-api.ap-northeast-1.amazonaws.com/prod
    volumes:
      - .:/var/task
    entrypoint: [""]
    command: ["python", "test_all_endpoints_direct.py"]
    ports:
      - "8000:8000"
