AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'YFinance API - 株式データ取得API'

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        PYTHONPATH: /opt/python

Resources:
  YFinanceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      BinaryMediaTypes:
        - image/png
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  YFinanceFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          # 環境変数は後で動的に設定されるため、ここでは空にする
          API_GATEWAY_URL: ""
      Events:
        # ベースURL - Swagger UI表示
        GetSwaggerUI:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /
            Method: get
        SearchStocks:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /search
            Method: get
        GetInfo:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /info
            Method: get
        GetChart:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /chart
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest

Outputs:
  YFinanceApiUrl:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${YFinanceApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
    Export:
      Name: YFinanceApiUrl

  YFinanceFunctionArn:
    Description: 'YFinance Lambda Function ARN'
    Value: !GetAtt YFinanceFunction.Arn
    Export:
      Name: YFinanceFunctionArn

  YFinanceFunctionName:
    Description: 'YFinance Lambda Function Name'
    Value: !Ref YFinanceFunction
    Export:
      Name: YFinanceFunctionName