AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'YFinance API - 株式データ取得API'

Globals:
  Function:
    Timeout: 60
    MemorySize: 1024
    Environment:
      Variables:
        PYTHONPATH: /opt/python

Resources:
  YFinanceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      BinaryMediaTypes:
        - image/png
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  YFinanceFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Timeout: 60
      Architectures:
        - x86_64
      Environment:
        Variables:
          # 環境変数は後で動的に設定されるため、ここでは空にする
          API_GATEWAY_URL: ""
      Events:
        # ベースURL - Swagger UI表示
        GetSwaggerUI:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /
            Method: get
        SearchStocks:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /search
            Method: get
        GetTickerDetail:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /tickerDetail
            Method: get
        GetBasic:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /ticker/basic
            Method: get
        GetPrice:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /ticker/price
            Method: get
        GetHistory:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /ticker/history
            Method: get
        GetFinancials:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /ticker/financials
            Method: get
        GetAnalysts:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /ticker/analysts
            Method: get
        GetHolders:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /ticker/holders
            Method: get
        GetEvents:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /ticker/events
            Method: get
        GetNews:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /ticker/news
            Method: get
        GetNewsRss:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /news/rss
            Method: get
        GetOptions:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /ticker/options
            Method: get
        GetSustainability:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /ticker/sustainability
            Method: get
        GetHome:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /home
            Method: get
        GetChart:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /chart
            Method: get
        GetRankingsStocks:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /rankings/stocks
            Method: get
        GetRankingsSectors:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /rankings/sectors
            Method: get
        GetRankingsCrypto:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /rankings/crypto
            Method: get
        GetMarketsIndices:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /markets/indices
            Method: get
        GetMarketsCurrencies:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /markets/currencies
            Method: get
        GetMarketsCommodities:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /markets/commodities
            Method: get
        GetMarketsStatus:
          Type: Api
          Properties:
            RestApiId: !Ref YFinanceApi
            Path: /markets/status
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest

Outputs:
  YFinanceApiUrl:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${YFinanceApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
    Export:
      Name: YFinanceApiUrl

  YFinanceFunctionArn:
    Description: 'YFinance Lambda Function ARN'
    Value: !GetAtt YFinanceFunction.Arn
    Export:
      Name: YFinanceFunctionArn

  YFinanceFunctionName:
    Description: 'YFinance Lambda Function Name'
    Value: !Ref YFinanceFunction
    Export:
      Name: YFinanceFunctionName
